baseURL = 'https://tripletjake.dev/'
languageCode = 'en-us'
title = 'Ton Tosirikul'
theme = 'typo'





[params]
description = "A Tech Blog"
theme = 'auto'
colorPalette = 'default'
listSummaries = true
homeIntroTitle = 'Hi there 👋'
homeIntroContent = """
I’m Ton, also known as Jake — just two names for the same person. 
I'm a software engineer, partly because I enjoy solving problems — and partly because it pays well enough to let me live in the costly city of Bangkok.  

This blog isn’t just about what I learn as a developer — it’s also a space where I share my thoughts, experiences, and reflections on life. Whether it’s tech, travel, or everyday moments, I write to connect, reflect, and occasionally make sense of it all.
"""

[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "~"

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.social]]
name = "github"
url = "https://github.com/tontosirikul"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/user/ton.tosirikul"